### ISSUE TITLE
The PV, PVC and DV of the virtual machine are backed up in the velero restic mode, and problems occur during the restore

### ISSUE THREAD

**Issue by UltimateJava** [kubevirt/kubevirt-velero-plugin#117]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>  /kind bug

**What happened**:

- When I restore the virtual machine with velero, I find that the virtual machine cannot be started. The PVC status is as follows:

`  Normal   Provisioning          86m (x44 over 3h39m)  rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-786866b564-r5jm8_fd7a9b7e-c7cd-449f-b1a6-1436c8f19d1f  External provisioner is provisioning volume for claim "vm/test-pvc-dvbrglpn"
  Warning  ProvisioningFailed    63m (x14 over 82m)    rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-786866b564-r5jm8_c05622ec-0de5-4c69-88c9-8c55cd0d3ffe  failed to provision volume with StorageClass "rook-ceph-block": error getting handle for DataSource Type VolumeSnapshot by Name cdi-tmp-513bb2a9-34b0-4f5e-8d89-761998a25d1a: error getting snapshot cdi-tmp-513bb2a9-34b0-4f5e-8d89-761998a25d1a from api server: volumesnapshots.snapshot.storage.k8s.io "cdi-tmp-513bb2a9-34b0-4f5e-8d89-761998a25d1a" not found
  Normal   Provisioning          3m24s (x30 over 82m)  rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-786866b564-r5jm8_c05622ec-0de5-4c69-88c9-8c55cd0d3ffe  External provisioner is provisioning volume for claim "vm/test-pvc-dvbrglpn"
  Normal   ExternalProvisioning  64s (x2982 over 12h)  persistentvolume-controller                                                                                 waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
`

- The status of the virtual machine is as follows:
`test-dvbrglpn         2d22h   WaitingForVolumeBinding   False`
**What you expected to happen**:
The pvc is restored successfully, and the virtual machine starts normally
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by Ramya1507** [comment]
@UltimateJava , How you are taking backup of VM/VMI/DV through restic.

We could not do it. We are installing as below. Anything we are missing

velero install --provider aws --bucket velero --secret-file credentials-velero --backup-location-config region=us-east-1,s3ForcePathStyle="true",s3Url=http://10.233.54.48:9000 ^Cuse-node-agent  --plugins velero/velero-plugin-for-aws:v1.1.0,quay.io/kubevirt/kubevirt-velero-plugin:v0.6.1 --use-volume-snapshots=false -n velero --uploader-type restic

**Comment by 27149chen** [comment]
I have the same issue.

problem lies with the dataSource(dataSourceRef) field. When restoring the pvc, it will stuck in pending state because no dataSource exists
```
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: volume-import-source-0262b8d8-a4e2-4131-9ae4-6a6747429cda
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: volume-import-source-0262b8d8-a4e2-4131-9ae4-6a6747429cda
  resources:
    requests:
      storage: 10Gi
```

```
Events:
  Type    Reason                Age                   From                                                                                                        Message
  ----    ------                ----                  ----                                                                                                        -------
  Normal  Provisioning          2m26s                 rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-7f6b88897c-llwfs_0506e147-80b3-4e94-9c65-ab7b080bc616  External provisioner is provisioning volume for claim "default/example-import-dv"
  Normal  Provisioning          2m26s                 external-provisioner                                                                                        Assuming an external populator will provision the volume
  Normal  ExternalProvisioning  17s (x10 over 2m26s)  persistentvolume-controller                                                                                 Waiting for a volume to be created either by the external provisioner 'rook-ceph.rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
```
