### ISSUE TITLE
Please reopen issue 117

### ISSUE THREAD

**Issue by 27149chen** [kubevirt/kubevirt-velero-plugin#213]
Please reopen issue #117, thanks

**Comment by ShellyKa13** [comment]
Hi @27149chen I saw your comment in #117 : https://github.com/kubevirt/kubevirt-velero-plugin/issues/117#issuecomment-1918529629
What you describe is definitely not the same issue as in issue 117.
So can you please describe how the issue you commented happened to you? how to reproduce, yamls, etc.. thanks!

**Comment by ShellyKa13** [comment]
your data source in this case is using pvc populators volumeimportsource as source, which is not what happens in the other issue. I want to know how to reproduce this since its not the same.

**Comment by 27149chen** [comment]
yes, the original pvc is created by a dataVolume, which will set the dataSource in pvc spec as a volumeimportsource. But the volumeimportsource is a temp object which will be deleted when population is done. When backup and restore this pvc to a new cluster, It will get stuck while waiting for the dataSource, and the solution is removing field dataSource and dataSourceRef

**Comment by ShellyKa13** [comment]
We have tests that have pvc that were populated this way and they work fine. Thats why I want you to describe exactly your scenario and how to reproduce please. Providing yamls and steps to reproduce.

**Comment by ShellyKa13** [comment]
Closing since there was no replay. feel free to open again if you reproduce providing relevant information and yamls.
