### ISSUE TITLE
Provide a configuration that allows velero backups to be successful with excluded pvc/datavolume

### ISSUE THREAD

**Issue by 30787** [kubevirt/kubevirt-velero-plugin#259]
**Is your feature request related to a problem? Please describe**:
Velero(kubervirt-velero plugin) backups of ocp vm fail when pvc/datavolume is excluded from backups. 
Backup applications with own data mover prefer to use velero for metadata backup and backup/restore pvc/datavolume on its own.
Currently kubevirt-velero plugin fails velero backup when pvc is excluded from backup:
https://github.com/kubevirt/kubevirt-velero-plugin/blob/main/pkg/util/util.go

**Describe the solution you'd like**:
Request is to allow successful velero/kubevirt-velero backup when pvc/datavolume is excluded (ex-using some EXTERNAL_DM env variable or any other configurable approach) 

**Describe alternatives you've considered**:
It will be great if you have any workaround for current behavior.

**Comment by alromeros** [comment]
Hey @30787, thanks for reporting this! We created a Jira story to track this issue https://issues.redhat.com/browse/CNV-47224. We'll start working on it as soon as possible.

**Comment by 30787** [comment]
Thanks @alromeros. @ShellyKa13  Looking forward to testing this feature once it is available with oadp 1.4.2

**Comment by 30787** [comment]
Thanks @alromeros. @ShellyKa13 Looking forward to testing this feature once it is available with oadp 1.4.2
