### ISSUE TITLE
Ability to power on/off vm during restore

### ISSUE THREAD

**Issue by 30787** [kubevirt/kubevirt-velero-plugin#294]
VM resource gets backed up based on the state of the vm during backup. Request is to have the ability to power on/off vm during restore using a label in restorejob.

**Comment by 30787** [comment]
@alromeros @mhenriks Can you please confirm if this change would be available with the kubevirt-velero-plugin image that would be part of Jan release of oadp 1.4.2 or earlier.

**Comment by alromeros** [comment]
Addressed in https://github.com/kubevirt/kubevirt-velero-plugin/pull/306 and backported to 0.7 in https://github.com/kubevirt/kubevirt-velero-plugin/pull/310. Closing the issue, thanks @30787 for the request.
/close
