### ISSUE TITLE
Kubevirt 0.49 support

### ISSUE THREAD

**Issue by kaovilai** [kubevirt/kubevirt-velero-plugin#54]
Document support for Kubevirt v0.49

**Comment by brybacki** [comment]
Hi, Thanks for reporting. 

What exactly do you mean? Just the update of the README.MD?

**Comment by kaovilai** [comment]
If it's verified to work then yes.

**Comment by brybacki** [comment]
Tested:
https://github.com/kubevirt/kubevirt-velero-plugin/pull/63

Will update the readme, and then bump kubevirt to even more recent version.
