### ISSUE TITLE
non kubevirt pods not given to next RestoreItemAction for processing

### ISSUE THREAD

**Issue by kaovilai** [kubevirt/kubevirt-velero-plugin#59]
For awareness, people who enable kubevirt-velero-plugin on velero deployments prior to https://github.com/vmware-tanzu/velero/pull/4890 may experience restore errors if their pod depends on another velero plugin to process.

https://github.com/kubevirt/kubevirt-velero-plugin/blob/603ee7e9d7f91549bb5b1c39a607b10d0747c7a4/pkg/plugin/pod_restore_item_action.go#L45
triggers the bug fixed by referenced PR.

**Comment by brybacki** [comment]
Thanks for information. That is good to know
